#ifndef __GAME_MATCH_SETUP_PLAYER_CONTROL_TRANSITION_H_
#define __GAME_MATCH_SETUP_PLAYER_CONTROL_TRANSITION_H_

#include "mssbTypes.h"

void transitionToPlayerControl(void);

#endif // !__GAME_MATCH_SETUP_PLAYER_CONTROL_TRANSITION_H_
