#ifndef __GAME_ANIMATION_SCENE_EFFECTS_H_
#define __GAME_ANIMATION_SCENE_EFFECTS_H_

#include "mssbTypes.h"

void fn_3_BA538(void);
void fn_3_BA7F4(void);
void fn_3_BB07C(void);
void fn_3_BB15C(void);
void fn_3_BB454(void);
void fn_3_BB7F4(void);
void fn_3_BBBC4(void);
void spriteAnimations(void);
void fn_3_BC224(void);
void fn_3_BC25C(void);
void fn_3_BC274(void);
void animateDustCloudsBehindFielder_Runner(void);
void maybeFireworks(void);
void fn_3_BC850(void);
void fn_3_BC888(void);
void drawSun(void);
void fn_3_BD1D4(void);
void sunRelated(void);
void setSunLocation(void);
void fn_3_BD4F0(void);
void animationRelated(void);
void fn_3_BD6AC(void);
void fn_3_BD758(void);
void fn_3_BD7D0(void);
void fn_3_BD7D8(void);
void fn_3_BD7DC(void);
void fn_3_BD80C(void);
void fn_3_BD8D8(void);
void fn_3_BD8FC(void);
void fn_3_BDCA4(void);
void fn_3_BDE14(void);
void fn_3_BDF74(void);
void fn_3_BE140(void);
void setContactWordSprite(void);
void fn_3_BE1D4(void);
void fn_3_BEFF8(void);
void fn_3_BF070(void);
void pauseStateOnStadiums(void);
void pauseAnimations(void);
void fn_3_BF20C(void);
void fn_3_BF238(void);
void maybeHudRelated(void);
void maybeLoadHUDObjectFromMemory(void);
void fn_3_BF8F8(void);
void fn_3_BFB3C(void);
void fn_3_BFDA4(void);
void fn_3_C0134(void);

#endif // !__GAME_ANIMATION_SCENE_EFFECTS_H_
