#ifndef __GAME_FIELDING_FIELDER_H_
#define __GAME_FIELDING_FIELDER_H_

#include "mssbTypes.h"
#include "game/UnknownHomes_Game.h"

typedef struct _AutoMovementFunction {
    /*0x0*/ s32 code;
    /*0x4*/ void (*fn)(int fielderIndex);
} AutoMovementFunction;

extern AutoMovementFunction autoMovementFunctions[29];

void autoMovement10_HasBall(int fielderIndex);

void knockOut_setPosAndVelo(int fielderIndex);
int processFielderKnockout(int fielderIndex, sAng knockOutAngle);
void fielderOnFirePosAndVelo(int fielderIndex);
void maybeCastleFireballBurn(int fielderIndex, int fireballType);
int fn_3_258D8(int fielderIndex);
void runningCatch_updatePositionAndVelocity(int fielderIndex);
void mag_BirdoSlidingCatchSetCoordinates(int fielderIndex);
void fielderMovement_VelocityDuringCatchAnimations(int fielderIndex);
void calculateBobble(int fielderIndex);
void updateVariablesPostCatch(int fielderIndex);
void processFielderAutoCatch(void);
void fn_3_27738(int fielderIndex);
void fn_3_27764(int fielderIndex);
void catchAnimationProgression(int fielderIndex);
int clamberCheckCatch(int fielderIndex);
int wallJumpSOmething3(int fielderIndex);
void wallJumpInitialization(void);
void divingCatch(void);
int uncalledattemptJumpingCatch(int fielderIndex);
void checkForAndSetFielderWallActionsOrDives(void);
int ballThrownToEmptyBaseCatchAttempt(int fielderIndex);
int fn_3_2ACD8(int fielderIndex, int index);
void catchThrownBallFun(void);
void fn_3_2B5C0(int fielderIndex);
int checkIfRunningCatchOccurs(int fielderIndex);
int checkIfCatchOccurs(int fielderIndex);
void fn_3_2C238(int fielderIndex, int catchAnimation, int framesCountDown, int autoCatchOnlyInd, int fastBattedBallInd);
void evaluateFlyBallCatch(int fielderIndex);
void checkForCatchBallAction(void);
void minigameDashUpdateFieldingVals(void);
void unused_FUN_8066bf88(int fielderIndex);
int determineBestFrameForFielder(int fielderIndex);
void fn_3_2D308(int fielderIndex);
void updateFielderPositionBasedOnBallState(int fielderIndex);
void unused_FUN_8066c7fc(int fielderIndex);
void autoMovement28_minigameDashRelated3(int fielderIndex);
void autoMovement27_minigameDashRelated2(int fielderIndex);
void autoMovement26_minigameRelated1(int fielderIndex);
void fn_3_2DDB4(void);
void fn_3_2E41C(void);
void toyfieldRelated(void);
void miniGameFielding(void);
void fn_3_2EA88(void);
void minigameDashUpdateFieldingVariables(void);
void miniGameDash(void);
void jumpSetPosAndVelo(int fielderIndex);
void fn_3_2F7D4(int fielderIndex);
void wallSplat_setPosAndVelo(int fielderIndex);
void setClamberPos(int fielderIndex);
void clamberJumpOffWall(int fielderIndex);
void fn_3_300B8(int fielderIndex);
int clamberInitialization(int fielderIndex);
int walljump_calculateJumpedOffWallPositionAndVelocity(int fielderIndex);
void moveFieldersFromDugoutToStartingPositions(void);
void fn_3_308B8(int fielderIndex, f32 x, f32 z);
void fn_3_30A58(void);
void fielding_prePitchAutomovement(void);
void fielding_atBat_SetSomeAutomovements_callCollisionFn(void);
void atBat_Fielders(void);
void fn_3_31678(void);
void fn_3_31A3C(void);
void fielderActionsOnSteal(void);
void stealSetFielders(void);
void determineSelectedfielderOnIFHit_Dribbler(void);
BOOL fn_3_327F4(void);
void selectInitialFielders_linedriveThroughPitcher(void);
void setInitialFielderMovements_foulBall(void);
void chooseSecondaryFielderFromClosestOutfielder(void);
void fn_3_33458(void);
void setInitialFielderMovements_generalCase(int noSecondaryFielderLogic);
void fn_3_33D9C(void);
void determinePrimaryAndSecondaryOutFielders(int *primaryFielder, int *secondaryFielder);
void setInitialFielderMovements_DeepFly(void);
void humanTeamFieldingFirstFrameAfterHit(void);
void decideHowToTrackFoulBall(void);
void autoMovement16_trackFoulBall(int fielderIndex);
void setPlayerWhoCanInterceptThrow(void);
int SelectClosestFielder2(f32 x, f32 z);
int fn_3_365D0(int fielderIndexA, int fielderIndexB, int fielderIndexC, f32 x, f32 z);
int selectBestFielder(int fielderIndexA, int fielderIndexB, int flag, f32 x, f32 z);
int SelectBetterFielder(int fielderIndexA, int fielderIndexB, int flag, f32 x, f32 z);
void fn_3_3740C(void);
void unused_FUN_8067661c(void);
void selectClosestFielderBasedOnFutureCoord(int frame);
int fn_3_378B4(void);
void SelectOptimalFielder(void);
void fn_3_38234(void);
void selectAssignClosestFielder2(void);
void setNewSelectedFielder_determinePriorSelectedFielder_sAutoMovement(int newFielder, int useHumanControlMovement);
void HandleMiddleInfieldSelection(void);
void fielderSelect_tertiaryFielderExists_determine2FieldersToKeep(void);
void updateBallLandedFielderSelection(void);
void updateInAirFielderSelection(void);
void unused_FUN_80678e58(void);
void updateFielderSelection(void);
void fn_3_3A1FC(int fielderIndex);
void setFielderVelocity_someSituation(int fielderIndex);
void moveFielder_CheckForAndSetJump(int fielderIndex);
void fn_3_3AAF8(int fielderIndex);
void fn_3_3ABF0(int fielderIndex);
void updateFielderMovementIfNoBall(int fielderIndex);
void autoMovement21_23_humanControlInitialSelectedFielders(int fielderIndex);
void autoMovement15_selectedFielderOnLooseBall(int fielderIndex);
void fn_3_3B764(void);
void fn_3_3B99C(void);
void liveBallFielderControlHumanTeam(void);
void checkIfPlayerNeedsToMoveToCatchBall(int fielderIndex);
void autoMovement19_foulBall(int fielderIndex);
void autoMovement0_stayStill_exceptForSpecialActions(int fielderIndex);
int fn_3_3C270(int fielderIndex);
int fn_3_3C484(int fielderIndex);
int runOffBaseOverride(int fielderIndex);
int fn_3_3CB8C(int fielderIndex);
void autoMovement9_OffBase_coverHome(int fielderIndex);
void autoMovement17_runningOffField(int fielderIndex);
void autoMovement12_stopBetweenInstructions(int fielderIndex);
int setFielderLocToBeNearBase(int fielderIndex);
void autoMovement14_infieldSupport(int fielderIndex);
void autoMovement20_pitcherLinedriveRelated(int fielderIndex);
void fn_3_3E468(void);
void knockoutRelated_Grounder_Liner(void);
void knockoutRelated_FlyBall(void);
void knockoutRelated(void);
void uncalled(void);
void fn_3_3F24C(void);
void fn_3_3F760(void);
void fn_3_3FCF0(BOOL useComputedAngle);
void fn_3_402A8(void);
void fn_3_40C04(void);
void fn_3_40D54(void);
void fn_3_40D88(void);
void aITeamFieldingFirstFrameAfterHit(void);
void fn_3_417D4(int fielderIndex);
void fielderAIAssignmentRelated(int mode);
void fielderAISomething(void);
void decideWhenToLeaveFunction2_16_18(int fielderIndex);
void fn_3_42850(int fielderIndex);
void fn_3_42A00(int fielderIndex);
void fn_3_42BD0(int fielderIndex);
void updateFielderPosition(int fielderIndex);
void setIntendedLocToInterceptBall(int fielderIndex);
void fielderTrackingBall_updateVariables(void);
void fielderTrackingBall_initialVariableSetting(void);
void autoMovement2_18_goTowardsBall_phase2(int fielderIndex);
void autoMovement4_AI_goTowardsHitBall(int fielderIndex);
void autoMovement3_goTowardsHitBall_AITeam(int fielderIndex);
void fn_3_4597C(int fielderIndex);
void autoMovement25_readyToInterceptThrownBall(int fielderIndex);
void updateFielderValuesSubFunction1_cuttoffRelated(void);
s32 fn_3_46688(f32* outX, f32* outZ);
s32 fn_3_468DC(f32* outX, f32* outZ);
void checkIfCutoffIsntAtThrowDestination(int fielderIndex);
int setCutoffLocationToStandAt(int fielderIndex, f32* outX, f32* outZ);
int fn_3_47628(void);
void setInitialFielderMovements_cutoffs(void);
void fn_3_480B8(int fielderIndex);
void fn_3_483CC(int fielderIndex);
void autoMovement5(int fielderIndex);
void autoMovement11_cutoff_setInitialLocation(int fielderIndex);
void secondaryOutfielderWhenToStopMoving(int fielderIndex);
void setSecondaryFielderToBe12mFromDropSpotToSupport(int fielderIndex, VecXYZ* out);
void autoMovement24_goTowardsHitBall_humanTeam(int fielderIndex);
void fn_3_49EA8(int fielderIndex);
void updateFielderValuesSubFunction3_empty(void);
void autoMovementDetermineWhatToDo(int fielderIndex, int arg1);
void setInitialFielderMovements_restOfFielders(void);
void setIntendedLocationAheadOfBallPath(int fielderIndex, f32* outX, f32* outZ);
void autoMovement13_GoTowardsBallAsBackUp(int fielderIndex);
void autoMovement6_outfielderNoCatch_Phase2(int fielderIndex);
void autoMovement7_8_outfiederNoCatch_Phase1(int fielderIndex);
void fn_3_4B8D0(int fielderIndex);
void updateSomeAutoMovementAssignments(void);
void setInitialFielderMovements_CoverBases(void);
void fn_3_4CFB0(void);
void autoMovement1_coverBase(int fielderIndex);
int fn_3_4DB84(int fielderIndex);
void bobbleDirection(int fielderIndex);
void findClosestFieldersToLooseBallAndAssignToGoGetIt(void);
void checkForAndHandleLooseBalls(void);
void aISetFielderWithBallIndex(void);
void knockoutRelated_subFn(int fielderIndex, int flag);
void setCatcherCatchStrategy_distToLandingSpot(int fielderIndex);
void setFielderCatchStrategy_calcFramesToGetToDropSpot(void);
int fn_3_50898(int fielderIndex, f32* outX, f32* outZ);
void fielderMovement_adjustPlaceToStandForBallBouncingOffWall(int fielderIndex, f32* outX, f32* outZ);
int fn_3_50DD8(int fielderIndex, f32* outX, f32* outZ, int flag);
void updateSprintPointers(void);
int adjustPlayerPosOutsideFoulLine(int fielderIndex, VecXYZ* out);
int updateFielderPosition_checkFielderCollision(int fielderIndex, VecXYZ* out);
int setZoneAwayFromHome(f32 x, f32 z);
f32 fn_3_52084(int fielderIndex, f32 x, f32 z);
void calculateMinDiveDistAndEndingCoords(int fielderIndex, int numFrames, f32 dirX, f32 dirZ,
                                          f32* outX, f32* outZ, f32* outDist);
int fRunningTimeToDestinationPlus7(int fielderIndex, f32 x, f32 z);
void setFielderVelocity(int fielderIndex);
void setFielderAutoCoords(int fielderIndex, f32 x, f32 z);
void fn_3_530EC(int fielderIndex);
int updateFielderPositionAndVelocityForSpecialActions(int fielderIndex);
void setStandingOnBaseVariables(int fielderIndex);
void fielderMovementRelated(int fielderIndex);
void minigameFieldingRelated_collisions(void);
void fielding_handleCollisionsAndSpecialActions(void);
void fn_3_54900(int fielderIndex);
void updateFielderDirectionFacing(void);
void fn_3_55370(void);
void fn_3_555AC(int fielderIndex);
void handleBodyCheck2(int fielderIndex);
void fielder_endOfInning_deadball_updateCounters(void);
void fielderUpdateChasingRunnerValues(int fielderIndex);
void updateFielder_SpecificValuesEachFrame(void);
void liveBallUpdateFieldingValues(void);
void updateOutfielderPositionBasedOnBallState(void);
void processFielderJumpAI(int fielderIndex);
void aITeamFielding_SelectCharWithHand(void);
void updateFielderMovementAndPosition(void);
void liveBallFielderControlAITeam(void);
void fielderResetAndStoreValuesEachFrame(void);
void setDefaultInMemFielder(void);
void initializeMiniGameCharacters(void);
void fielding_setStartingCoordinates(int fielderIndex, f32* outX, f32* outZ);
void pPRelated(void);
void resetInMemFielders(void);
void initializeFielderConstants(void);
void initFielders(void);

#endif // !__GAME_FIELDING_FIELDER_H_
