#ifndef __GAME_FIELDING_FIELDER_AI_H_
#define __GAME_FIELDING_FIELDER_AI_H_

#include "mssbTypes.h"

void fielderAIDecideWhatRunnerToTarget(void);
void fn_3_A1D04(void);
void fn_3_A1DA0(void);
void fn_3_A1F3C(void);
void fielderAIWeirdSituation(void);
void canThrowOutRunnerWhoNeedsToTagUp(void);
void throwOutRunnerTaggingUpInd(void);
void genericPlayOnRunnerOffBase(void);
void fn_3_A295C(void);
void fn_3_A2B6C(void);
void fn_3_A2C9C(void);
void fn_3_A2DDC(void);
void fn_3_A2FD8(void);
void fn_3_A31E8(void);
void fn_3_A32B8(void);
void fielderAIOutfieldPlayAttemptInd(void);
void fn_3_A36BC(void);
void fn_3_A372C(void);
void fn_3_A3768(void);
void fn_3_A37BC(void);
void fn_3_A384C(void);
void fn_3_A3B30(void);
void fn_3_A3C00(void);
void fielderAIChaseRunner(void);
void fn_3_A4158(void);
void fn_3_A41E8(void);
void fielderAIMakePlay(void);
void fieldingAIPlayStrategy(void);
void throwTimeToBase(void);
void fn_3_A53DC(void);
void runnerTimeToCoverBase(void);
void fieldingAIThrowOrChase(void);
void howManyFramesTheRunnerIsOutOfReach(void);
void fn_3_A67E8(void);
void estimatedThrowFramesBetweenTwoPoints(void);
void fn_3_A6ABC(void);
void fn_3_A6D48(void);
void tagRelated(void);
void tagOutValues(void);
void fielderHasBall(void);
void checkForBufferedThrow(void);
void fielderControl_classifyControlStickDirection(void);
void setRunnerChasingAfter(void);
void fielderChasingAI(void);
void runnerTagUpOrBatterTo1B(void);
void maybeUnused_SetThrowSpeedType2(void);
void fn_3_A89D4(void);
void knockBallLoose(void);
void fielderBodyCheck_setStatus_Pos_Velo(void);
void fielderKnockback(void);
void setFielder215(void);
void autoMovement10_HasBall(void);
void fn_3_AAA3C(void);
void fn_3_AABF8(void);
void fn_3_AAC84(void);
void setCutoffThrowTargetLocation(void);
void fn_3_AB554(void);
void initializeThrowAngle_Speed_Length(void);
void makeThrowVariables(void);

#endif // !__GAME_FIELDING_FIELDER_AI_H_
