#ifndef __GAME_STADIUM_STADIUM_DK_JUNGLE_H_
#define __GAME_STADIUM_STADIUM_DK_JUNGLE_H_

#include "mssbTypes.h"

void fn_3_EE100(void);
void fn_3_EE388(void);
void fn_3_EE67C(void);
void fn_3_EE96C(void);
void fn_3_EEB94(void);
void fn_3_EECF4(void);
void fn_3_EEE3C(void);
void fn_3_EEF24(void);
void fn_3_EEFA4(void);
void fn_3_EEFD0(void);
void klaptrapHitAnimation(void);
void fn_3_EF218(void);
void fn_3_EF21C(void);
void fn_3_EF3D4(void);
void jungleStadiumObjectRelated(void);
void isPosOutsideKlaptrapZone(void);
void fn_3_EF7B4(void);
void fn_3_EF800(void);
void fn_3_EF890(void);
void dkKlaptrapLaunchedUpdate(void);
void fn_3_EFB54(void);
void fn_3_F0184(void);
void dkKlaptrapChaseUpdate(void);
void dkKlaptrapRoamUpdate(void);
void klaptrapControl(void);
void fn_3_F13F8(void);
void klaptrapCTRLSetup(void);
void maybeGharialCTRLRel(void);
void fn_3_F1674(void);
void fn_3_F1750(void);
void fn_3_F18A4(void);
void handleDKJungleBarrel(void);
void dkBarrelSpawnGroundDust(void);
void fn_3_F22FC(void);
void dkBarrel_collisionWithFielder(void);
void fn_3_F2724(void);
void dkBarrelAdvanceMotion(void);
void fn_3_F2FFC(void);
void dkBarrelLaunch(void);
void fn_3_F37BC(void);
void fn_3_F38D4(void);
void fn_3_F3A04(void);
void fn_3_F3A5C(void);
void fn_3_F3AE0(void);
void fn_3_F3BB0(void);
void dkBarrelSmokeUpdate(void);
void fn_3_F3EFC(void);
void fn_3_F42A0(void);
void fn_3_F466C(void);
void fn_3_F469C(void);
void dkJungleBarrelCannonCutsceneUpdate(void);
void fn_3_F4BA0(void);
void fn_3_F4C4C(void);
void fn_3_F4D00(void);
void fn_3_F4DAC(void);
void handleBarrelFiring(void);
void dkJungleBarrelCannonUpdate(void);
void fn_3_F5C30(void);
void fn_3_F5E78(void);
void fn_3_F5EFC(void);
void fn_3_F5F28(void);
void fn_3_F5F4C(void);
void processJungleObjectCollisions(void);
void fn_3_F6504(void);
void fn_3_F65C8(void);
void updateDKJungleObjBoundingBoxes(void);
void maybeBarrelCTRLRel(void);
void fn_3_F6A94(void);
void updateDKJungleControl(void);
void fn_3_F6FCC(void);
void loadDKJungle(void);

#endif // !__GAME_STADIUM_STADIUM_DK_JUNGLE_H_
