#!/usr/bin/env python3
"""
Write docs/ghidra_name_conflicts.md: every place where the repo and the Ghidra
project BOTH have a real name for the same thing and the names disagree.

These are deliberately not auto-resolved. A disagreement means one of the two
authors was wrong (or they named different aspects of the same thing), and
choosing needs game knowledge -- unlike the placeholder->real renames in
ghidra_rename.py, which are unambiguous wins.

Run after `ghidra_query.py refresh` or after any renaming pass.

Usage:
    python tools/ghidra_conflicts.py
"""
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import ghidra_query as gq  # noqa: E402
import ghidra_rename as gr  # noqa: E402

REPO = gq.REPO
OUT = REPO / "docs" / "ghidra_name_conflicts.md"

# Structs worth comparing: repo name[:ghidra name]. Only ones whose total size
# matches Ghidra exactly -- a size disagreement means the layouts differ and
# lining fields up by offset would produce noise, not conflicts.
STRUCTS = ["AIStruct", "GameControlsStruct", "InMemBallType:InMemBall"]


def _same_name(repo_name, ghidra_name):
    """True when the two are the same name, ignoring Ghidra's uncertainty mark.

    `drawStadium` vs `drawStadium?` is not a naming disagreement -- the `?` says
    the Ghidra author was unsure, which the sanitizer renders as a `_maybe`
    suffix. Comparing with that suffix intact would report hundreds of
    false conflicts.
    """
    s = gr.sanitize(ghidra_name)
    if s is None:
        return False
    variants = {s.lower()}
    if s.endswith(gr.UNCERTAIN_SUFFIX):
        variants.add(s[:-len(gr.UNCERTAIN_SUFFIX)].lower())
    return repo_name.lower() in variants


def symbol_conflicts():
    cs = gq.config_symbols(with_meta=True)
    fsyms = gq.load_symbols("in_game")
    dsyms = gq.load_data("in_game")
    rows = []
    for name, (addr, section, meta, path) in sorted(cs.items(), key=lambda kv: kv[1][0]):
        is_fn = "type:function" in meta
        hit = fsyms.get(addr) if is_fn else dsyms.get(addr)
        if hit is None:
            continue
        g = hit[1] if is_fn else hit[2]
        if not g or gr.G_AUTO.match(g) or gr.REPO_PLACEHOLDER.match(name):
            continue
        if gr.sanitize(g) is None or _same_name(name, g):
            continue
        rows.append((addr, name, g, "function" if is_fn else "data"))
    return rows


def struct_conflicts():
    rows = []
    for spec in STRUCTS:
        out = subprocess.run([sys.executable, str(REPO / "tools" / "ghidra_struct_diff.py"), spec],
                             capture_output=True, text=True).stdout
        repo_name = spec.split(":")[0]
        for line in out.splitlines():
            m = re.match(r"\s+(0x[0-9A-F]+)\s+repo (\S+)\s+ghidra (.+)$", line)
            if not m:
                continue
            off, r, g = m.group(1), m.group(2), m.group(3).strip()
            # Not a real disagreement if the repo name is just the sanitized
            # form of the Ghidra one (`AIControlFlag` vs `AIControlFlag?`).
            base = re.sub(r"\[.*", "", r)
            if _same_name(base, g):
                continue
            rows.append((repo_name, off, r, g))
    return rows


def main():
    sym = symbol_conflicts()
    struct = struct_conflicts()
    L = []
    L.append("# Ghidra name conflicts\n")
    L.append("Generated by `tools/ghidra_conflicts.py`. These are places where **both** the")
    L.append("repo and the Ghidra project have a real (non-placeholder) name for the same")
    L.append("thing, and the two names disagree. Nothing here was changed automatically --")
    L.append("picking a winner needs a human who knows the game.\n")
    L.append("Ghidra names are shown verbatim, so they may contain characters that are")
    L.append("illegal in C (`?` `/` `,` `(` `)` `=`). Sanitize before adopting one; a")
    L.append("trailing `?` in Ghidra means the author was unsure, which is itself a signal")
    L.append("that the repo name may be the better one.\n")
    L.append("Regenerate after a `ghidra_query.py refresh` or any renaming pass.\n")

    L.append("## Struct fields (%d)\n" % len(struct))
    L.append("Only structs whose total size matches Ghidra exactly are compared, so these")
    L.append("are true same-offset disagreements rather than layout drift.\n")
    L.append("| struct | offset | repo | ghidra |")
    L.append("|---|---|---|---|")
    for s, o, r, g in struct:
        L.append("| `%s` | %s | `%s` | `%s` |" % (s, o, r, g))

    L.append("\n## Symbols (%d: %d functions, %d data)\n" % (
        len(sym), sum(1 for x in sym if x[3] == "function"),
        sum(1 for x in sym if x[3] == "data")))
    L.append("| address | kind | repo | ghidra |")
    L.append("|---|---|---|---|")
    for a, n, g, k in sym:
        L.append("| `0x%08x` | %s | `%s` | `%s` |" % (a, k, n, g))

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8", newline="\n")
    print("wrote %s: %d struct + %d symbol conflicts" % (
        OUT.relative_to(REPO), len(struct), len(sym)))


if __name__ == "__main__":
    main()
